package com.fieldops.mobile

import com.facebook.react.BaseReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.model.ReactModuleInfo
import com.facebook.react.module.model.ReactModuleInfoProvider
import com.fieldops.mobile.evidence.FieldOpsFilesModule
import com.fieldops.mobile.location.FieldOpsLocationModule

/**
 * Registers FieldOps' own Turbo Modules (specs in src/services/native, generated by codegen
 * from `codegenConfig` in apps/mobile/package.json).
 */
class FieldOpsPackage : BaseReactPackage() {

  override fun getModule(name: String, reactContext: ReactApplicationContext): NativeModule? =
      when (name) {
        FieldOpsLocationModule.NAME -> FieldOpsLocationModule(reactContext)
        FieldOpsFilesModule.NAME -> FieldOpsFilesModule(reactContext)
        else -> null
      }

  override fun getReactModuleInfoProvider(): ReactModuleInfoProvider = ReactModuleInfoProvider {
    listOf(FieldOpsLocationModule.NAME, FieldOpsFilesModule.NAME).associateWith { name ->
      ReactModuleInfo(
          name,
          name,
          false, // canOverrideExistingModule
          false, // needsEagerInit
          false, // isCxxModule
          true, // isTurboModule
      )
    }
  }
}
