/**
 * Where binary files (job evidence) live. The database stores metadata and the object's key;
 * the bytes go here (docs/evidence.md, "Storage").
 *
 * One implementation exists: local disk (LocalDiskObjectStorage), which is enough for local
 * development and a single-instance deployment with a persistent volume. An S3-compatible
 * implementation replaces it behind this interface when the API runs on more than one
 * instance; callers do not change.
 */
export interface ObjectStorage {
  /** Stores the bytes under `key`, replacing any object with that key. */
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  /** The object's bytes, or null if there is none. */
  get(key: string): Promise<Buffer | null>;
  /** Removes the object. Idempotent: a missing object is not an error. */
  delete(key: string): Promise<void>;
}

/** Injection token for ObjectStorage. */
export const OBJECT_STORAGE = Symbol('OBJECT_STORAGE');

/**
 * Keys are generated by the server (for example `evidence/<jobId>/<evidenceId>.jpg`), never
 * taken from requests. They are still checked, so a bug can never address a file outside
 * the storage root: lower-case letters, digits, `-`, `_`, `.` and `/`-separated segments,
 * no empty, `.` or `..` segment.
 */
const KEY_PATTERN = /^[a-z0-9_-][a-z0-9._-]*(\/[a-z0-9_-][a-z0-9._-]*)*$/;

export function isValidStorageKey(key: string): boolean {
  return (
    key.length <= 300 &&
    KEY_PATTERN.test(key) &&
    key.split('/').every(segment => segment !== '.' && segment !== '..')
  );
}
