import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import type {
  AddJobEvidenceFields,
  AddJobNoteRequest,
  AssignJobRequest,
  CancelJobRequest,
  JobCommandRequest,
  SendJobMessageRequest,
} from '@fieldops/types';
import { Type } from 'class-transformer';
import { IsObject, IsUUID, ValidateNested } from 'class-validator';

import {
  DeviceLocationDto,
  JOB_LIMITS,
  OccurredAtField,
  PresentOnly,
  TextField,
} from './job-fields.js';

export class JobIdParamDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID('all', { message: 'Job ID must be a UUID.' })
  readonly id: string;
}

export class JobEvidenceParamDto extends JobIdParamDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID('all', { message: 'Evidence ID must be a UUID.' })
  readonly evidenceId: string;
}

export class AssignJobDto implements AssignJobRequest {
  @ApiProperty({
    format: 'uuid',
    description:
      'An active user with the WORKER role (see GET /api/v1/users/workers).',
  })
  @IsUUID('all', { message: 'Worker ID must be a UUID.' })
  readonly workerId: string;
}

export class CancelJobDto implements CancelJobRequest {
  @PresentOnly()
  @TextField('Reason', JOB_LIMITS.cancellationReason, {
    required: false,
    example: 'Customer rescheduled the visit.',
  })
  readonly reason?: string;
}

/** Body of start and complete: optionally where the worker was at that moment. */
export class JobCommandDto implements JobCommandRequest {
  @ApiPropertyOptional({
    type: DeviceLocationDto,
    description:
      "The phone's position fix, if it had one. Recorded with the history entry; the " +
      'server computes the distance from the job site itself.',
  })
  @PresentOnly()
  @IsObject({ message: 'Location must be an object.' })
  @ValidateNested()
  @Type(() => DeviceLocationDto)
  readonly location?: DeviceLocationDto;
}

export class AddJobNoteDto implements AddJobNoteRequest {
  @ApiProperty({
    format: 'uuid',
    description:
      'Generated by the device, so an offline note keeps its ID. Sending the same note again is a no-op.',
  })
  @IsUUID('all', { message: 'Note ID must be a UUID.' })
  readonly id: string;

  @TextField('Note', JOB_LIMITS.note, {
    example: 'Compressor replaced. Customer asked for a follow-up visit.',
  })
  readonly body: string;

  @OccurredAtField()
  readonly occurredAt: string;
}

/**
 * The text fields of the multipart evidence upload. The file is the `file` part; its name
 * and declared type are ignored (the server detects the type from the bytes).
 */
export class AddJobEvidenceDto implements AddJobEvidenceFields {
  @ApiProperty({
    format: 'uuid',
    description:
      'Generated by the device, so offline evidence keeps its ID. Uploading it again is a no-op.',
  })
  @IsUUID('all', { message: 'Evidence ID must be a UUID.' })
  readonly id: string;

  @OccurredAtField('Captured at')
  readonly capturedAt: string;
}

export class SendJobMessageDto implements SendJobMessageRequest {
  @ApiProperty({
    format: 'uuid',
    description:
      'Generated by the sending device, so a message sent offline keeps its ID. Sending it again is a no-op.',
  })
  @IsUUID('all', { message: 'Message ID must be a UUID.' })
  readonly id: string;

  @TextField('Message', JOB_LIMITS.message, {
    example: 'The customer wants the old unit taken away. OK?',
  })
  readonly body: string;

  @OccurredAtField()
  readonly occurredAt: string;
}
