import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import type {
  AddJobEvidenceFields,
  AddJobNoteRequest,
  AssignJobRequest,
  CancelJobRequest,
  ChecklistAnswer,
  DeclineJobRequest,
  FailJobRequest,
  JobCommandRequest,
  LineCount,
  OrderLineInput,
  PaymentInput,
  RejectJobRequest,
  RescheduleJobRequest,
  SendJobMessageRequest,
  SubmitJobRequest,
  VerifyJobRequest,
} from '@fieldops/types';
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  IsArray,
  IsBoolean,
  IsEnum,
  IsInt,
  IsObject,
  IsUUID,
  Matches,
  Max,
  Min,
  ValidateNested,
} from 'class-validator';

import { AmountField } from '../../common/dto/fields.js';
import { PaymentMethod } from '../job-enums.js';

import {
  DeviceLocationDto,
  JOB_LIMITS,
  OccurredAtField,
  PresentOnly,
  ScheduledAtField,
  TextField,
} from './job-fields.js';

export class JobIdParamDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID('all', { message: 'Job ID must be a UUID.' })
  readonly id: string;
}

export class JobEvidenceParamDto extends JobIdParamDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID('all', { message: 'Evidence ID must be a UUID.' })
  readonly evidenceId: string;
}

export class AssignJobDto implements AssignJobRequest {
  @ApiProperty({
    format: 'uuid',
    description:
      'An active user with the WORKER role (see GET /api/v1/users/workers).',
  })
  @IsUUID('all', { message: 'Worker ID must be a UUID.' })
  readonly workerId: string;
}

export class CancelJobDto implements CancelJobRequest {
  @PresentOnly()
  @TextField('Reason', JOB_LIMITS.cancellationReason, {
    required: false,
    example: 'Customer rescheduled the visit.',
  })
  readonly reason?: string;
}

/** Body of start and complete: optionally where the worker was at that moment. */
export class JobCommandDto implements JobCommandRequest {
  @ApiPropertyOptional({
    type: DeviceLocationDto,
    description:
      "The phone's position fix, if it had one. Recorded with the history entry; the " +
      'server computes the distance from the job site itself.',
  })
  @PresentOnly()
  @IsObject({ message: 'Location must be an object.' })
  @ValidateNested()
  @Type(() => DeviceLocationDto)
  readonly location?: DeviceLocationDto;
}

export class AddJobNoteDto implements AddJobNoteRequest {
  @ApiProperty({
    format: 'uuid',
    description:
      'Generated by the device, so an offline note keeps its ID. Sending the same note again is a no-op.',
  })
  @IsUUID('all', { message: 'Note ID must be a UUID.' })
  readonly id: string;

  @TextField('Note', JOB_LIMITS.note, {
    example: 'Compressor replaced. Customer asked for a follow-up visit.',
  })
  readonly body: string;

  @OccurredAtField()
  readonly occurredAt: string;
}

/**
 * The text fields of the multipart evidence upload. The file is the `file` part; its name
 * and declared type are ignored (the server detects the type from the bytes).
 */
export class AddJobEvidenceDto implements AddJobEvidenceFields {
  @ApiProperty({
    format: 'uuid',
    description:
      'Generated by the device, so offline evidence keeps its ID. Uploading it again is a no-op.',
  })
  @IsUUID('all', { message: 'Evidence ID must be a UUID.' })
  readonly id: string;

  @OccurredAtField('Captured at')
  readonly capturedAt: string;
}

export class SendJobMessageDto implements SendJobMessageRequest {
  @ApiProperty({
    format: 'uuid',
    description:
      'Generated by the sending device, so a message sent offline keeps its ID. Sending it again is a no-op.',
  })
  @IsUUID('all', { message: 'Message ID must be a UUID.' })
  readonly id: string;

  @TextField('Message', JOB_LIMITS.message, {
    example: 'The customer wants the old unit taken away. OK?',
  })
  readonly body: string;

  @OccurredAtField()
  readonly occurredAt: string;
}

const REASON = 500;

export class DeclineJobDto implements DeclineJobRequest {
  @TextField('Reason', REASON, { example: 'I am on leave that day.' })
  readonly reason: string;
}

export class FailJobDto extends JobCommandDto implements FailJobRequest {
  @TextField('Reason', REASON, { example: 'Shop closed; owner unreachable.' })
  readonly reason: string;
}

export class ChecklistAnswerDto implements ChecklistAnswer {
  @ApiProperty({ format: 'uuid' })
  @IsUUID('all', { message: 'Checklist item must be a valid ID.' })
  readonly itemId: string;

  @ApiProperty()
  @IsBoolean({ message: 'Answer each item with true or false.' })
  readonly checked: boolean;

  @PresentOnly()
  @TextField('Item note', REASON, { required: false })
  readonly note?: string;
}

export class LineCountDto implements LineCount {
  @ApiProperty({ format: 'uuid' })
  @IsUUID('all', { message: 'Line must be a valid ID.' })
  readonly lineId: string;

  @ApiProperty({ minimum: 0 })
  @IsInt({ message: 'Quantities must be whole numbers.' })
  @Min(0, { message: 'Quantities must be 0 or more.' })
  @Max(1_000_000)
  readonly quantity: number;
}

export class OrderLineInputDto implements OrderLineInput {
  @ApiProperty({ format: 'uuid' })
  @IsUUID('all', { message: 'Product must be a valid ID.' })
  readonly productId: string;

  @ApiProperty({ minimum: 1 })
  @IsInt({ message: 'Quantities must be whole numbers.' })
  @Min(1, { message: 'Quantities must be 1 or more.' })
  @Max(1_000_000)
  readonly quantity: number;
}

export class PaymentInputDto implements PaymentInput {
  @ApiProperty({
    format: 'uuid',
    description:
      'Generated by the device: submitting the same payment again is a no-op.',
  })
  @IsUUID('all', { message: 'Payment ID must be a UUID.' })
  readonly id: string;

  @AmountField('Amount')
  readonly amount: number;

  @ApiProperty({ enum: Object.values(PaymentMethod) })
  @IsEnum(PaymentMethod, {
    message: `Method must be one of ${Object.values(PaymentMethod).join(', ')}.`,
  })
  readonly method: PaymentMethod;

  @PresentOnly()
  @TextField('Reference', 100, { required: false, example: 'UTR0012345678' })
  readonly reference?: string;

  @OccurredAtField('Collected at')
  readonly collectedAt: string;
}

/**
 * The worker's result. The parts required depend on the operation type
 * (@fieldops/shared/requirements); unknown parts are refused.
 */
export class SubmitJobDto extends JobCommandDto implements SubmitJobRequest {
  @PresentOnly()
  @TextField('Note', JOB_LIMITS.note, { required: false })
  readonly note?: string;

  @ApiPropertyOptional({ type: [ChecklistAnswerDto] })
  @PresentOnly()
  @IsArray()
  @ArrayMaxSize(JOB_LIMITS.checklistItems)
  @ValidateNested({ each: true })
  @Type(() => ChecklistAnswerDto)
  readonly checklist?: ChecklistAnswerDto[];

  @ApiPropertyOptional({ type: [LineCountDto] })
  @PresentOnly()
  @IsArray()
  @ArrayMaxSize(100)
  @ValidateNested({ each: true })
  @Type(() => LineCountDto)
  readonly lineCounts?: LineCountDto[];

  @ApiPropertyOptional({ type: [OrderLineInputDto] })
  @PresentOnly()
  @IsArray()
  @ArrayMaxSize(100)
  @ValidateNested({ each: true })
  @Type(() => OrderLineInputDto)
  readonly orderLines?: OrderLineInputDto[];

  @ApiPropertyOptional({ type: PaymentInputDto })
  @PresentOnly()
  @IsObject({ message: 'Payment must be an object.' })
  @ValidateNested()
  @Type(() => PaymentInputDto)
  readonly payment?: PaymentInputDto;
}

export class VerifyJobDto implements VerifyJobRequest {
  @PresentOnly()
  @TextField('Note', REASON, { required: false })
  readonly note?: string;

  @ApiPropertyOptional({
    example: '2026-10-31',
    description:
      'ORDER_COLLECTION: when the new order must be paid (default: 30 days after today).',
  })
  @PresentOnly()
  @Matches(/^\d{4}-\d{2}-\d{2}$/, { message: 'Due date must be YYYY-MM-DD.' })
  readonly orderDueDate?: string;
}

export class RejectJobDto implements RejectJobRequest {
  @TextField('Reason', REASON, {
    example: 'The receipt photo is unreadable; please take another.',
  })
  readonly reason: string;
}

export class RescheduleJobDto implements RescheduleJobRequest {
  @ScheduledAtField(true)
  readonly scheduledAt: string;

  @PresentOnly()
  @TextField('Reason', REASON, { required: false })
  readonly reason?: string;
}
