import type { ApiErrorCode } from '@fieldops/types';

/**
 * Runtime values for the shared ApiErrorCode union. The `satisfies` clause fails compilation
 * if this object and @fieldops/types drift apart (a code missing here, or an unknown one).
 */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  JOB_NOT_EDITABLE: 'JOB_NOT_EDITABLE',
  INVALID_ASSIGNEE: 'INVALID_ASSIGNEE',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  NOT_IN_ORGANIZATION: 'NOT_IN_ORGANIZATION',
  ORGANIZATION_SUSPENDED: 'ORGANIZATION_SUSPENDED',
  INVALID_REFERENCE: 'INVALID_REFERENCE',
  REQUIREMENTS_NOT_MET: 'REQUIREMENTS_NOT_MET',
  AMOUNT_EXCEEDS_BALANCE: 'AMOUNT_EXCEEDS_BALANCE',
  DUPLICATE_PAYMENT_REFERENCE: 'DUPLICATE_PAYMENT_REFERENCE',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  EVIDENCE_LIMIT_REACHED: 'EVIDENCE_LIMIT_REACHED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const satisfies { readonly [Code in ApiErrorCode]: Code };

export type { ApiErrorCode };
