/**
 * Job contracts shared by the API (which implements them in its DTO classes) and the mobile
 * app (which consumes them). See docs/api.md, "Jobs".
 */

/**
 * Lifecycle of a job. Allowed transitions are enforced by the server's job state machine
 * (apps/api/src/jobs/domain/job-state-machine.ts):
 *
 *   PENDING ──assign──▶ ASSIGNED ──start──▶ IN_PROGRESS ──complete──▶ COMPLETED
 *      │                  │  ▲                  │
 *      │                  └──┘ reassign         │
 *      └──────cancel──────┴────────cancel───────┴──▶ CANCELLED
 *
 * COMPLETED and CANCELLED are terminal.
 */
export const JobStatus = {
  /** Created, not assigned to anyone yet. */
  PENDING: 'PENDING',
  /** Assigned to a worker who has not started it. */
  ASSIGNED: 'ASSIGNED',
  /** The assigned worker started it. */
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];

export const JobPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export type JobPriority = (typeof JobPriority)[keyof typeof JobPriority];

/**
 * Operations on an existing job. Every job response lists the ones the signed-in user may
 * perform right now (`allowedActions`), computed by the server from the user's role, their
 * relationship to the job and its status. Clients show exactly these and nothing else.
 */
export const JobAction = {
  START: 'start',
  COMPLETE: 'complete',
  ASSIGN: 'assign',
  EDIT: 'edit',
  CANCEL: 'cancel',
  DELETE: 'delete',
  /** Add a field note (the assigned worker; works offline). */
  NOTE: 'note',
  /** Attach a photo as evidence (the assigned worker; works offline). */
  EVIDENCE: 'evidence',
  /** Post a message on the job (the assigned worker and managers; offline for workers). */
  MESSAGE: 'message',
} as const;

export type JobAction = (typeof JobAction)[keyof typeof JobAction];

/** Entries of a job's append-only history. */
export const JobEventType = {
  CREATED: 'CREATED',
  /** Assigned or reassigned; `assignee` names the worker. */
  ASSIGNED: 'ASSIGNED',
  STARTED: 'STARTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type JobEventType = (typeof JobEventType)[keyof typeof JobEventType];

/** The minimal public view of a user referenced by a job. */
export interface UserSummary {
  readonly id: string;
  readonly firstName: string;
  readonly lastName: string;
}

/** A worker a manager can assign jobs to. */
export interface WorkerSummary extends UserSummary {
  readonly email: string;
}

export interface GeoPoint {
  /** WGS 84 degrees, -90 to 90. */
  readonly latitude: number;
  /** WGS 84 degrees, -180 to 180. */
  readonly longitude: number;
}

export interface JobChecklistItem {
  readonly id: string;
  /** 0-based display order. */
  readonly position: number;
  readonly label: string;
}

/** A job as shown in lists. */
export interface JobSummary {
  readonly id: string;
  readonly title: string;
  readonly customerName: string;
  readonly address: string;
  /** ISO 8601 timestamp. */
  readonly scheduledAt: string;
  readonly priority: JobPriority;
  readonly status: JobStatus;
  readonly assignedWorker: UserSummary | null;
  /** Incremented on every change. Send it back with edits (optimistic concurrency). */
  readonly version: number;
  /** ISO 8601 timestamp. */
  readonly updatedAt: string;
  readonly allowedActions: readonly JobAction[];
}

export interface JobHistoryEntry {
  readonly id: string;
  readonly type: JobEventType;
  readonly fromStatus: JobStatus | null;
  readonly toStatus: JobStatus;
  /** Who did it. */
  readonly actor: UserSummary;
  /** The worker the job was assigned to (ASSIGNED entries only). */
  readonly assignee: UserSummary | null;
  /** ISO 8601 timestamp. */
  readonly createdAt: string;
}

/** A note the assigned worker recorded in the field. Append-only. */
export interface JobNote {
  /** Generated by the device, so an offline note keeps its ID forever. */
  readonly id: string;
  readonly body: string;
  readonly author: UserSummary;
  /** Device time when the note was written (informational: device clocks can be wrong). */
  readonly occurredAt: string;
  /** Server time when the note was received (authoritative order). */
  readonly createdAt: string;
}

/**
 * A position fix reported by the worker's phone when they start or complete a job. Device
 * data: it can be inaccurate or spoofed, so it is recorded for review, never used to
 * authorize anything (docs/location.md).
 */
export interface DeviceLocation {
  readonly latitude: number;
  readonly longitude: number;
  /** Radius of 68% confidence, in meters, as reported by Android. */
  readonly accuracyMeters: number;
  /** ISO 8601 device time of the fix. */
  readonly capturedAt: string;
}

/** Where a job was started or completed. */
export interface ActionLocation extends DeviceLocation {
  /**
   * Distance from the job site in meters, computed by the server from the reported fix and
   * the job's coordinates (null when the job has no coordinates). On the device, a pending
   * command shows the phone's own estimate until the server's value arrives.
   */
  readonly distanceMeters: number | null;
}

export const EVIDENCE_CONTENT_TYPES = ['image/jpeg', 'image/png'] as const;
export type EvidenceContentType = (typeof EVIDENCE_CONTENT_TYPES)[number];

/** A photo attached to a job. The bytes are fetched separately (authorized download). */
export interface JobEvidence {
  /** Generated by the device, so offline evidence keeps its ID from capture to server. */
  readonly id: string;
  /** Detected by the server from the file's bytes, never taken from the client. */
  readonly contentType: EvidenceContentType;
  readonly sizeBytes: number;
  readonly width: number;
  readonly height: number;
  readonly uploadedBy: UserSummary;
  /** Device time of capture (informational). */
  readonly capturedAt: string;
  /** Server receipt time. */
  readonly createdAt: string;
}

/** A message on a job between the assigned worker and managers. Append-only. */
export interface JobMessage {
  /** Generated by the sending device, so an offline message keeps its ID. */
  readonly id: string;
  readonly body: string;
  readonly author: UserSummary;
  /** Device time when it was written (informational). */
  readonly occurredAt: string;
  /** Server receipt time (authoritative order). */
  readonly createdAt: string;
}

/** A job with everything the details screen needs. */
export interface JobDetail extends JobSummary {
  readonly description: string | null;
  readonly location: GeoPoint | null;
  /** Instructions from the manager. */
  readonly notes: string | null;
  readonly checklist: readonly JobChecklistItem[];
  readonly cancellationReason: string | null;
  readonly createdBy: UserSummary;
  /** ISO 8601 timestamps. */
  readonly createdAt: string;
  readonly startedAt: string | null;
  readonly completedAt: string | null;
  readonly cancelledAt: string | null;
  /** Oldest first. */
  readonly history: readonly JobHistoryEntry[];
  /** Worker field notes, in the order the server received them. */
  readonly fieldNotes: readonly JobNote[];
  /** Where the worker was when they started the job (null if no fix was available). */
  readonly startLocation: ActionLocation | null;
  /** Where the worker was when they completed the job. */
  readonly completeLocation: ActionLocation | null;
  /** Photos, in the order the server received them. */
  readonly evidence: readonly JobEvidence[];
  /** The most recent messages (at most 100), oldest first. */
  readonly messages: readonly JobMessage[];
}

/**
 * Everything a worker's device keeps offline: the jobs assigned to them that are open, plus
 * those closed recently. A job missing from the snapshot is no longer the worker's to see.
 */
export interface JobWorkingSet {
  readonly jobs: readonly JobDetail[];
  /** ISO 8601 server time the snapshot was taken. */
  readonly generatedAt: string;
}

/** One page of GET /api/v1/jobs. `nextCursor` is null on the last page. */
export interface JobPage {
  readonly items: readonly JobSummary[];
  readonly nextCursor: string | null;
}

export interface CreateJobRequest {
  readonly title: string;
  readonly description?: string;
  readonly customerName: string;
  readonly address: string;
  readonly location?: GeoPoint;
  /** ISO 8601 timestamp. */
  readonly scheduledAt: string;
  /** Defaults to NORMAL. */
  readonly priority?: JobPriority;
  readonly notes?: string;
  /** Item labels, in order. */
  readonly checklist?: readonly string[];
}

/**
 * Partial update of manager-owned fields. `version` must match the job's current version,
 * otherwise the server answers 409 VERSION_CONFLICT. `null` clears an optional field.
 * Status is never edited directly: use the action endpoints.
 */
export interface UpdateJobRequest {
  readonly version: number;
  readonly title?: string;
  readonly description?: string | null;
  readonly customerName?: string;
  readonly address?: string;
  readonly location?: GeoPoint | null;
  readonly scheduledAt?: string;
  readonly priority?: JobPriority;
  readonly notes?: string | null;
  /** Replaces the whole checklist. Only before the job is started. */
  readonly checklist?: readonly string[];
}

export interface AssignJobRequest {
  readonly workerId: string;
}

export interface CancelJobRequest {
  readonly reason?: string;
}

/** Body of POST /jobs/:id/start and /complete. Both fields are optional. */
export interface JobCommandRequest {
  /** The worker's position at that moment, if the phone could get one. */
  readonly location?: DeviceLocation;
}

/** Multipart fields of POST /jobs/:id/evidence (besides the `file` part). */
export interface AddJobEvidenceFields {
  /** A UUID generated by the device for the new evidence. */
  readonly id: string;
  /** ISO 8601 device time of capture with a time zone. */
  readonly capturedAt: string;
}

export interface SendJobMessageRequest {
  /** A UUID generated by the sending device. */
  readonly id: string;
  readonly body: string;
  /** ISO 8601 device time with a time zone. */
  readonly occurredAt: string;
}

export interface AddJobNoteRequest {
  /** A UUID generated by the device for the new note. */
  readonly id: string;
  readonly body: string;
  /** ISO 8601 device time with a time zone. */
  readonly occurredAt: string;
}
